### ISSUE TITLE
Investigate margin of error for decompose_depolarizer with jax

### ISSUE THREAD

**Issue by kenjim21** [Jashcraf/katsu#25]
![Screenshot 2024-08-16 180213](https://github.com/user-attachments/assets/5dbc40aa-0e64-46b5-840c-568798f2247d)

This is the margin of difference between the matrices when I print them

**Comment by kenjim21** [comment]
Appears that each non-zero final result is off at the 6th decimal compared to the zeroes

**Comment by Jashcraf** [comment]
For reference my Jax machine precision is ~1e-16, so it’s probably real

```python
>>> import jax.numpy as np
>>> np.finfo(float).eps
np.float64(2.220446049250313e-16)
```
